### ISSUE TITLE
official website is down

### ISSUE THREAD

**Issue by meidachen** [shinke-li/Campus3D#3]
Hi,

I'm currently unable to access the website and can't download the data, could you please direct me on how I can get the data?

Thanks,

Meida Chen

**Comment by flyingtango** [comment]
Hi Meida,

Which part of the data do you need? The website is under maintenance and I will send you the file directly.

**Comment by meidachen** [comment]
Thank you for your response. I actually want all data for training and testing point cloud segmentation networks. My email address: mchen.toledo@gmail.com

Thank you so much!

**Comment by flyingtango** [comment]
The website is restored and you can go download the dataset now. Thanks for following our project.

**Comment by meidachen** [comment]
Thank you and I have downloaded the dataset. I have another question about the image collections. In your paper, you mentioned, "More detailed settings can be found in the supplementary document." But I wasn't able to locate any supplementary document online, could you please provide me with the overlap between images, the flight altitudes, and also how many images you collected for each area?

In addition, I'm wondering would it be possible for you to share all the source images?

Thank you for your help!!

**Comment by flyingtango** [comment]
The supplementary material is available in the description page. We don't have a plan to release the original images because of the project license and the complexity of the cleaning process. I will let you know if there is a plan to update it later.
