### ISSUE TITLE
get point cloud of  building instances

### ISSUE THREAD

**Issue by yidahuang** [shinke-li/Campus3D#4]
Hi, thanks for your nice work! I would like to use your data in building reconstruction, and I need the point cloud of building instances.
Could u please tell me how to extract this kind of data from the raw data?

**Comment by flyingtango** [comment]
Hi,

We're glad you're interested in our project! 

The instance label you are looking for is already available in our existing dense dataset in the [download page](https://3d.dataset.site/download), the directed download link is https://nusdataset.s3.ap-southeast-1.amazonaws.com/3d/Campus3D_dense.zip .

You can follow our guidelines for label extraction operations in the [Suppementry Materials and Reproduciblity Papers](https://3d.dataset.site/des).

Regards,
Zekun

**Comment by shinke-li** [comment]
More information can be found in #6
