### ISSUE TITLE
label extraction of dense dataset

### ISSUE THREAD

**Issue by Bitfultea** [shinke-li/Campus3D#5]
Hi, I'm trying to make use of the dense version of the dataset. The label format appears to be [N,23] with 23 labels. Could someone please tell me how to extract the labels from them. Thank you

**Comment by meidachen** [comment]
I have the same question, @Bitfultea  were you able to figure it out? Thanks!

I saw that on the description page, the figure showed that there are 23 new classes in the figure. I assume these are the 23 distinct classes shown in the figure, but could someone help to give the mapping between these 23 classes?

**Comment by shinke-li** [comment]
Hi, @Bitfultea @meidachen  , the mapping between 23 labels in the dense dataset and label names is shown in the updated file **label_convert.yaml** in **data**:

├── data
 |   ├── data_list.yaml
 |   ├── matrix_file_list.yaml
 |   ├── **label_convert.yaml**
 |   └──...

Furthermore, to obtain the 14 leaf labels in C5 level, you can use _'leaf_label':'index'_ in **label_convert.yaml** to index the 23 labels. The obtained leaf labels in C5 can be used to get labels in other levels.
