### ISSUE TITLE
Instance segmentation labels

### ISSUE THREAD

**Issue by meidachen** [shinke-li/Campus3D#6]
Is there a way we can get the instance labels?

**Comment by shinke-li** [comment]
Yes, you can access the instance label by [dense version](https://3d.dataset.site/download) of Campus3D dataset. The labels in this version are organized with 23 semantic classes as dimension of N x 23. For each semantic class, the integer number larger than 0 for each point (each row) does stand for the instance id of the point.

However, there are some classes being not countable or difficult to identify instance (like _ground_ or _driving road_), so the instance ids might not be quite meaningful. We provide the instance label mapping of C4 level in **data/label_convert.yaml**, where 4 labels can be used for instance segmentation.
