### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by BLUE-hub** [shinke-li/Campus3D#8]
Thank you for your outstanding work, when I tried to download the dataset, I found that the URL is unstable and does not jump to the download page. Is it possible to update the dataset website?

**Comment by shinke-li** [comment]
We were sorry for the broken download link, please use the following google drive link for the dataset:
https://drive.google.com/file/d/1hguF9ysO1ec9Q4aSmWw1KMmgXTRYI8NY/view?usp=drive_link

**Comment by BLUE-hub** [comment]
您好，感谢您的来信。您的邮件我已收到，谢谢！

--------------------------------------------------This is an automatic reply， confirming that your e-mail was received.Thank you

**Comment by shinke-li** [comment]
Please use the download links at: 
https://3d.nus.app/download/

**Comment by BLUE-hub** [comment]
您好，感谢您的来信。您的邮件我已收到，谢谢！

--------------------------------------------------This is an automatic reply， confirming that your e-mail was received.Thank you
